---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: http://github.com/abhi1-rithu2/flux-production

